//
//  Constants.swift
//  Layout
//
//  Created by James Tang on 9/7/15.
//  Copyright (c) 2015 James Tang. All rights reserved.
//

import UIKit
import QuartzCore

let strings : [String] = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ex dolor, imperdiet vel tellus sollicitudin, ultrices maximus nunc. Ut non vehicula magna. Etiam sit amet varius lectus, et luctus dui. Sed eget blandit turpis. Nullam laoreet at felis non fermentum. Integer elit sem, tempus eget ex non, mattis porta lorem. Sed ut quam vel nibh luctus bibendum quis sed mi.",
    "Fusce scelerisque rhoncus elementum. Maecenas ultricies est ex, ut varius mauris cursus at. Maecenas sollicitudin orci posuere, ultricies lacus vel, scelerisque nibh. Nullam a turpis a urna elementum posuere. Integer porttitor vestibulum urna lobortis tincidunt. Aliquam consectetur sem metus, et laoreet libero rutrum nec. Donec sed justo dapibus, mollis nibh volutpat, sollicitudin sem. Suspendisse tempor, velit ac ullamcorper pretium, sapien risus molestie enim, aliquam cursus ex massa a nisl. Duis gravida, diam eget rutrum sagittis, dui est malesuada mi, a dapibus eros odio sit amet tellus. Nunc porttitor nunc nec massa mollis, et pellentesque est egestas. Vivamus venenatis dignissim massa in euismod. Vestibulum rutrum ex a interdum varius. Donec convallis gravida dui eget viverra. Suspendisse tempor, lorem sit amet consequat mattis, libero ex dictum quam, eget iaculis felis velit eu nunc. Morbi eros lectus, aliquet at pulvinar sed, tempor malesuada elit. Integer blandit gravida felis.",
    "Nulla volutpat mauris id arcu sodales euismod. Aliquam feugiat metus libero. Sed eget velit fringilla, sagittis velit ac, sodales sem. Proin sed nulla tristique, pulvinar felis ac, vehicula mauris. Aenean imperdiet sem a dui scelerisque ultricies. Cras sagittis et purus et aliquet. Curabitur ac viverra turpis, quis convallis risus. Vivamus ullamcorper risus purus, id pellentesque massa bibendum at. Ut quis purus maximus, aliquet ex sed, aliquam ipsum. In aliquam lacinia luctus. Aliquam sed massa quis leo lobortis blandit vel quis elit. Praesent ac ligula non erat bibendum accumsan.",
    "Mauris eget consequat elit, facilisis efficitur mauris. Sed orci est, pharetra vitae orci ac, molestie elementum libero. Morbi non fringilla risus. Curabitur ipsum sapien, tempus quis sollicitudin eget, euismod sed justo. Nulla laoreet magna vitae lorem ullamcorper, venenatis placerat purus consequat. Aliquam odio justo, rhoncus ac aliquam faucibus, suscipit vitae leo. Integer at enim sed lectus imperdiet aliquam. Curabitur ac maximus nisi. Pellentesque dictum, enim ac accumsan posuere, mi tellus fermentum est, sed pulvinar nibh ante vitae orci. Nullam vitae nisi eget dolor placerat gravida eu at massa.",
    "Curabitur convallis, mauris at varius aliquet, velit est varius est, at interdum dui nunc eu justo. Donec pretium dictum odio, nec malesuada lectus finibus ac. Nullam tristique id diam ut imperdiet. Mauris ut diam at libero faucibus euismod. Phasellus lobortis a leo at auctor. Pellentesque at augue ut purus tempus bibendum vitae sit amet sapien. Suspendisse aliquam, nibh a suscipit fermentum, lorem velit volutpat ipsum, quis mattis neque ipsum et tortor. Duis pulvinar consequat nibh, quis porttitor magna aliquam non. Mauris volutpat nibh orci, non molestie felis porta ut. Cras interdum tempus turpis, vitae blandit felis ultrices vitae.",
    "Aliquam aliquet sem a lorem auctor laoreet. Praesent eget metus scelerisque, condimentum odio vitae, tincidunt arcu. Cras ut elementum quam, ac maximus neque. Sed risus tortor, ornare a risus hendrerit, fermentum sodales ipsum. Nunc vel tempor quam. Mauris metus ligula, mattis nec aliquet id, facilisis nec massa. Maecenas vestibulum consequat mauris, at tempor dui mattis ac. Fusce rhoncus pretium rhoncus. Aliquam ullamcorper tempus sapien non vulputate. Aliquam a condimentum dolor. Nam semper tincidunt sapien sed venenatis. Proin blandit eros dui, in vulputate est gravida ac. Praesent lectus urna, molestie vitae dapibus non, condimentum porttitor tellus. Mauris vitae placerat risus. Nullam vitae sem interdum dui maximus porttitor.",
    "Nam sit amet faucibus ante. Quisque vel massa justo. Aenean eget magna tortor. Praesent convallis ante consequat, hendrerit elit a, scelerisque leo. Pellentesque id diam et nulla imperdiet sagittis non nec sapien. In dictum metus pretium est porttitor lacinia. Etiam sagittis a felis eu cursus. Donec pharetra eu arcu et tristique. Donec pharetra orci ac aliquam ullamcorper. Vivamus semper odio vestibulum diam pellentesque, quis efficitur sapien feugiat. Mauris ac lacus vel neque pharetra blandit ac at nisi. Donec viverra augue dolor, sit amet posuere ex accumsan vel.",
    "Donec sodales at orci in faucibus. Suspendisse potenti. Vestibulum posuere porta justo, ac semper eros. Donec eleifend odio dictum, ullamcorper justo pulvinar, viverra sapien. Mauris eget ex at dolor commodo facilisis vitae et velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor arcu magna, eget varius urna dignissim a. Nam faucibus tortor eu augue imperdiet, non imperdiet nisi malesuada. Vestibulum bibendum lacus dapibus, ornare turpis semper, accumsan orci. Nunc at placerat nibh, id venenatis tellus. Fusce imperdiet fringilla quam, ut cursus est semper non. Ut tincidunt, ligula rhoncus dignissim ultricies, sem arcu congue turpis, ac sagittis erat risus at tellus. Morbi nec lorem lacus. Nulla facilisi.",
    "Vivamus ante risus, rhoncus id orci non, accumsan mattis tellus. Praesent tincidunt sem nibh, ut porta felis pretium vel. Nam at sodales sapien. Donec tincidunt mauris eget mi facilisis pellentesque. Fusce ac elementum nibh, nec consectetur elit. Morbi luctus auctor ornare. Etiam varius porttitor elit vitae tristique. Ut vestibulum nisl quis libero tincidunt fringilla. Cras non libero non ex condimentum aliquam id sit amet risus. Suspendisse dapibus velit ipsum, eu pharetra justo hendrerit sed.",
    "Aenean ullamcorper lectus sapien, at commodo nunc posuere et. Aliquam gravida metus vel elit vestibulum, non viverra justo facilisis. Nam lobortis volutpat fringilla. Pellentesque diam ipsum, molestie vel est eget, suscipit semper risus. Aliquam sollicitudin massa vel nulla tempus dictum. Donec cursus pharetra aliquam. Aliquam a pretium eros, at dictum ligula. Nulla iaculis auctor justo vitae feugiat. Vestibulum sit amet sapien sit amet ante interdum suscipit. Aliquam sed commodo ante.",
    "Aliquam vestibulum vestibulum mollis. Nam elementum, leo eget fermentum egestas, augue velit ullamcorper nisi, vitae mollis lacus ipsum in eros. Phasellus at condimentum libero, quis convallis enim. Nunc erat mauris, vulputate iaculis purus vitae, auctor fringilla purus. Morbi cursus hendrerit fringilla. Fusce tristique efficitur nulla vitae ornare. Nullam sollicitudin elit ut tincidunt ultricies.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed orci nec ipsum convallis sollicitudin non id mi. Cras aliquam justo id venenatis scelerisque. Cras porta euismod placerat. Maecenas accumsan, leo in ultrices consectetur, mi nulla tincidunt lacus, in maximus massa mauris vitae risus. Integer at finibus metus. Fusce mauris nibh, pharetra vitae nulla sed, pulvinar aliquet tellus. Suspendisse luctus tortor sapien, in gravida eros interdum vitae. Donec sit amet magna at quam aliquet consequat et non dolor. Integer tincidunt leo tortor, iaculis semper justo sagittis id. Donec porttitor mauris odio, ut vestibulum urna blandit vel. Mauris libero nibh, euismod maximus pharetra ut, molestie eget turpis.",
    "Etiam rutrum laoreet congue. Praesent ut turpis elementum, varius nunc at, volutpat nunc. Vivamus rutrum ante id justo tristique commodo. Mauris luctus velit ac dui venenatis, in auctor justo faucibus. Vestibulum accumsan ullamcorper nunc, et suscipit dolor sollicitudin at. Nulla consequat ipsum sed lectus aliquam, non ullamcorper neque feugiat. Duis egestas bibendum consectetur. Suspendisse eget interdum est, at cursus urna. Maecenas mollis varius mi nec interdum. Etiam rutrum maximus elit. Sed lobortis, odio sed semper luctus, ante est elementum urna, maximus dapibus velit risus sit amet ligula. Quisque cursus tristique lectus id faucibus. Duis mattis, tortor vel semper vestibulum, sem quam facilisis orci, non facilisis erat tortor vel dui. Suspendisse et sapien luctus, commodo lectus posuere, laoreet orci.",
    "In dignissim at nunc ac mollis. Suspendisse arcu diam, sagittis id dictum id, tincidunt id diam. Donec aliquam vestibulum nulla, quis ullamcorper risus tempus a. Etiam odio ligula, tincidunt at orci non, rutrum vehicula enim. Nullam dapibus sagittis tincidunt. Sed eu ante suscipit, rhoncus felis in, fermentum erat. Sed eu augue vel erat interdum viverra. Nulla facilisi. In in elit a justo convallis porta ac id purus. Nunc at quam diam. Quisque sit amet diam vestibulum, ornare arcu eget, consequat diam. Aenean elementum velit vel tortor viverra fermentum. Maecenas porttitor nisl sed nibh aliquam posuere. Quisque fermentum, libero a cursus pretium, neque dui pharetra orci, vitae pulvinar odio leo non nulla. Maecenas hendrerit, orci sit amet varius fringilla, nulla nisi ornare mauris, non tincidunt quam leo convallis orci. Vivamus vel consectetur erat, id tempor lectus.",
    "In a accumsan quam, in luctus ante. In a rutrum tellus. Ut vitae elit lacus. Nam bibendum lectus eget urna condimentum molestie. Aliquam blandit turpis non elit rhoncus fringilla. Maecenas vitae pellentesque lectus. Aenean lacus mauris, semper id dapibus a, rhoncus id sapien. Proin in dolor quis ligula mattis cursus. In ullamcorper nisl massa, ac pellentesque sapien interdum consequat. Sed dapibus id ex lacinia tempor. Praesent ac rhoncus urna, id rhoncus lacus. Vivamus nec finibus augue, at sagittis massa. Donec mattis sit amet sapien a dignissim. Sed rutrum egestas tempor. Suspendisse potenti.",
    "Vivamus ut laoreet neque. Cras est erat, venenatis finibus sapien sit amet, sollicitudin vestibulum nulla. Duis euismod viverra magna ac dignissim. Sed scelerisque scelerisque sapien malesuada condimentum. Phasellus laoreet vehicula dui fringilla accumsan. Mauris mauris leo, pulvinar a metus id, aliquet vehicula sapien. Pellentesque pulvinar a ipsum eget molestie. Fusce ipsum nulla, rutrum a lacinia id, eleifend ut massa. Morbi quis ipsum sit amet ligula facilisis ornare. Nunc quis tellus eleifend, pulvinar dolor eu, imperdiet tellus. Nullam in libero sollicitudin, interdum neque a, malesuada ante. Vestibulum sit amet eleifend mi. Quisque risus urna, vulputate ut urna et, luctus porta ipsum. Aenean ut convallis enim. Morbi nec diam commodo, rhoncus diam sed, gravida magna.",
    "Phasellus quis fermentum nibh. Curabitur congue, nulla et pellentesque varius, purus eros maximus ex, eget aliquam purus orci imperdiet sapien. Praesent suscipit risus id libero maximus, at efficitur neque congue. Curabitur vulputate, massa et fringilla varius, nibh turpis blandit turpis, posuere ornare massa turpis eu ex. Cras vel est a enim convallis efficitur. Nam feugiat euismod consectetur. Vivamus quis turpis nec nisl tempus finibus. Praesent id dolor a metus sodales fringilla sed id nulla. Vivamus ut eros vel mauris viverra eleifend. Curabitur vel mattis urna. Nunc ut odio purus. Ut non ipsum libero. Morbi massa libero, mollis eu porttitor nec, finibus eget ligula. Maecenas viverra aliquet diam, quis laoreet mi volutpat non. Sed aliquet ligula ut velit dapibus sollicitudin. Phasellus varius mattis bibendum.",
    "Duis eleifend augue quam, et imperdiet dui dignissim in. Donec condimentum risus et porta faucibus. Duis tellus libero, eleifend id metus in, gravida accumsan leo. Donec imperdiet vel eros vel pulvinar. Integer auctor, velit vel tincidunt facilisis, diam neque varius ex, in faucibus diam tortor a erat. Aliquam at ante non tellus malesuada faucibus. Fusce nulla turpis, suscipit et velit in, commodo fringilla nibh. Duis eget lacus aliquet, commodo purus id, pretium dolor. Integer quis purus urna. Suspendisse sagittis enim viverra erat feugiat, vel sodales ligula pellentesque. Nam tempor rutrum erat, at pretium mauris rhoncus nec. Quisque venenatis tincidunt orci, varius consectetur purus lobortis sit amet.",
    "Morbi facilisis euismod aliquet. Morbi accumsan consequat odio, non ornare ex posuere vel. Cras convallis est at pharetra finibus. Fusce ac congue neque. Vestibulum volutpat interdum sapien nec finibus. Nullam quis nunc felis. Nullam ullamcorper cursus magna, et lobortis augue varius mattis. Proin ullamcorper, lectus sit amet iaculis tempor, velit risus accumsan purus, ut tincidunt nibh lorem in est. Nullam massa leo, bibendum non laoreet non, vestibulum vitae metus. In at sem sit amet elit pretium interdum. Nunc ac tristique mi. Sed egestas sagittis orci id faucibus. Vestibulum vestibulum faucibus vulputate. Morbi finibus turpis scelerisque libero feugiat, eu gravida sapien semper. Nunc lacinia blandit facilisis.",
    "Vestibulum augue metus, dapibus ac volutpat eu, vehicula non ante. Morbi non justo vel arcu egestas tincidunt. Praesent ultricies tempus est eu malesuada. Aliquam erat volutpat. Suspendisse fringilla nisl eu tristique maximus. Phasellus dui orci, vulputate non sodales a, tincidunt sit amet arcu. Sed metus risus, pellentesque vitae vehicula at, pulvinar vel enim. Etiam vel laoreet augue. Donec at augue ac quam tincidunt vehicula. Maecenas iaculis pharetra arcu eu scelerisque. Maecenas malesuada massa vitae sapien molestie porta sed in nibh.",
    "Nunc et massa vitae tortor feugiat porttitor. Fusce commodo nibh sed malesuada pharetra. Fusce in rhoncus dui. Suspendisse efficitur porta lorem tempus elementum. Donec arcu odio, scelerisque ut pulvinar ac, elementum vel urna. Nam libero eros, feugiat vitae venenatis at, tempus in ligula. Sed ultricies dui quam. Donec nec leo vel augue elementum faucibus. Curabitur luctus rutrum risus, nec hendrerit neque maximus ut. Aenean scelerisque sem et dictum efficitur. Vivamus quis ante massa. Mauris id massa erat. Curabitur blandit felis odio, in maximus quam consectetur vel.",
    "Sed auctor mi nunc, non vehicula mauris luctus eget. Nunc lacinia dignissim posuere. Curabitur eu eros leo. Donec lectus risus, molestie vitae diam at, condimentum lobortis tortor. Cras pulvinar aliquam magna, et pharetra ligula. Cras hendrerit, felis vitae sollicitudin lobortis, tellus felis suscipit mi, id vehicula arcu nibh at nibh. Vestibulum porta rhoncus dolor nec auctor. Aliquam pulvinar finibus purus, a convallis sem viverra eu. Duis blandit volutpat ligula, ut euismod eros accumsan vel. Sed eu sem urna. Maecenas consectetur auctor sollicitudin. Curabitur porta magna enim, a pulvinar nunc imperdiet sed. Donec eget arcu leo.",
    "Aliquam erat volutpat. Pellentesque blandit iaculis arcu eu pharetra. Quisque ac nibh ante. Fusce in mauris mi. Etiam interdum arcu eu ex congue, quis tincidunt diam accumsan. Quisque ac fringilla metus, non maximus magna. Phasellus consequat molestie lacus sit amet placerat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ut cursus dui. Aliquam eget facilisis diam. Quisque malesuada tellus sit amet nisl dictum ultricies. Sed et rhoncus tortor, eget viverra tortor. Vivamus placerat ligula eu elit rutrum, sed porttitor odio cursus. Nullam at quam enim. Ut ut efficitur odio.",
    "Integer quam leo, porttitor vel finibus et, varius tristique dolor. Nulla eget dolor lacinia, lacinia augue vel, tempus risus. Pellentesque convallis lorem fermentum lacus condimentum placerat. Aenean fermentum diam in felis mollis tristique. Sed pretium ipsum ligula, sit amet placerat lectus euismod elementum. Vivamus et nisi lacus. Nulla est dui, pharetra quis malesuada ut, tincidunt sit amet sem. Fusce id ex sit amet dui tincidunt mollis.",
    "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam venenatis diam orci, scelerisque interdum ligula ullamcorper quis. Phasellus ullamcorper dolor a sagittis consequat. Fusce molestie ante eu est placerat fermentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam convallis sagittis vehicula. Vivamus metus tortor, suscipit sit amet lectus a, consequat viverra massa. Pellentesque mollis orci in lorem scelerisque, nec viverra nunc dapibus. Proin vestibulum, erat vitae consequat molestie, massa nisi volutpat augue, in volutpat mi diam euismod mauris.",
    "Cras enim metus, laoreet eu venenatis nec, lacinia eu urna. Donec euismod lobortis arcu eget tristique. Mauris in mauris vel justo vulputate mattis nec in nunc. Suspendisse convallis pulvinar dictum. Praesent at justo augue. Vivamus nec purus malesuada, gravida libero id, varius odio. Donec pretium lacus quis aliquam vestibulum.",
    "Integer rhoncus elit metus, in elementum eros maximus a. Duis placerat justo a tempor vehicula. Phasellus varius at ligula vitae commodo. Pellentesque eu sem vitae lectus accumsan interdum. Fusce nec venenatis tortor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi ante ligula, facilisis nec euismod nec, tempor ac magna.",
    "Mauris egestas, metus eu dignissim cursus, neque tortor mattis urna, sit amet interdum elit dolor at magna. Morbi vitae enim interdum, maximus lorem sit amet, egestas lacus. Cras lobortis quam ultricies enim euismod sollicitudin. Donec ac ante vitae sem interdum euismod. Aenean viverra massa quis erat consequat, ut varius elit pharetra. Praesent convallis iaculis bibendum. Aenean odio augue, vestibulum nec magna et, feugiat blandit leo. Maecenas urna velit, tincidunt nec sodales et, viverra vel odio. Aenean a tristique tellus, eget eleifend tortor. Morbi facilisis purus sed nibh ultricies, a consequat nunc porta. Donec ultrices neque eu nibh viverra, nec finibus metus porttitor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed tincidunt lectus ut nunc feugiat, eget scelerisque magna commodo.",
    "Morbi quis tristique leo. Proin tincidunt fringilla diam, sit amet eleifend mauris luctus et. Donec hendrerit tortor ac tellus sodales, eu aliquet ligula lobortis. Pellentesque at turpis purus. Morbi euismod eros libero, ac interdum diam placerat in. Praesent neque dui, faucibus eu porttitor rhoncus, elementum eget urna. Nunc porttitor imperdiet semper. Pellentesque volutpat ligula eu risus laoreet, nec bibendum metus semper. Nulla leo ante, fermentum ut volutpat quis, finibus quis turpis. Sed quis porttitor ex, sit amet euismod tellus. Maecenas in sollicitudin nisl.",
    "Sed sit amet lacus sed tellus dictum ornare et quis lectus. Proin ultrices nulla nec molestie tincidunt. Nulla ex urna, eleifend ac justo ac, cursus congue elit. Quisque dapibus vitae purus ut vehicula. Proin facilisis massa laoreet nisl porta convallis. Duis tincidunt egestas fermentum. Cras sagittis sapien in libero rhoncus laoreet.",
    "Etiam mauris ante, viverra at tortor a, vehicula eleifend lectus. Curabitur quis orci faucibus, consectetur leo sit amet, congue odio. Nunc luctus ligula ut elementum aliquet. Sed vitae tempor metus. Donec luctus eros ut nunc volutpat, in pellentesque elit fermentum. Vivamus vel hendrerit risus, in porta urna. Quisque tempus nunc sit amet varius posuere. Integer sed erat et orci scelerisque luctus sed ut nulla.",
    "Donec tempor ullamcorper tempor. Fusce placerat metus tellus, non tempus magna placerat ut. Nullam sed feugiat neque. Etiam rhoncus lectus ut lectus porta fringilla. Curabitur ut ex quis quam pulvinar tristique non sed urna. Fusce ultrices blandit urna ut finibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean sit amet magna quis metus mollis ornare. Cras sodales non libero ut faucibus. In sed sem vitae turpis egestas vulputate in vel ante. Pellentesque id mollis ex, at lobortis ligula. Integer rutrum viverra eros. Donec at mauris ultricies, condimentum dui quis, pharetra felis. Ut nunc mauris, viverra at justo sed, efficitur pretium magna. Cras consectetur nisi risus, vel fringilla leo tempor ut.",
    "In in nisi sodales, blandit nunc nec, feugiat risus. Nulla vestibulum aliquet ipsum, at pulvinar mi. Praesent ut velit ullamcorper, rhoncus nisi ullamcorper, dapibus odio. Proin nunc orci, molestie vitae libero et, imperdiet cursus tortor. Aenean dictum orci nisl, a iaculis leo hendrerit tincidunt. Quisque sit amet ligula risus. Sed erat nibh, ullamcorper a elit ac, iaculis faucibus lectus. Integer congue sagittis libero, dapibus convallis libero volutpat non. Sed quam sapien, mollis vel neque ut, lacinia bibendum sem. Duis aliquam nisi dui, quis rhoncus ipsum luctus ac. Nullam hendrerit quis lorem vitae tincidunt. Maecenas sed arcu vestibulum, placerat tortor elementum, venenatis est. Pellentesque elementum ligula vel lectus pharetra, at fringilla erat consectetur. Integer at velit placerat, finibus nisi id, luctus mi. Proin volutpat, nulla quis ornare pellentesque, metus neque posuere ex, ut tempor lacus ex at lacus. Maecenas mollis a massa ut pulvinar.",
    "Sed at magna hendrerit, dignissim quam ut, pulvinar sem. Etiam id scelerisque neque, ac feugiat nibh. Nulla sed tincidunt erat. Donec nec justo viverra neque auctor euismod quis ut eros. Nunc vel efficitur turpis, non consectetur nisl. In aliquet efficitur purus eu feugiat. Duis tincidunt nunc magna, eu interdum turpis sodales ac. Nulla facilisi.",
    "Proin maximus dui suscipit efficitur luctus. Fusce bibendum ligula fermentum enim dictum, non accumsan est consectetur. Ut rutrum cursus metus ut sodales. Fusce venenatis id neque eget rutrum. Proin ut ultrices purus. In leo purus, elementum nec venenatis in, convallis gravida enim. Etiam accumsan, justo vel accumsan faucibus, ex lectus pharetra ex, ac sollicitudin turpis tortor non orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Donec iaculis volutpat nunc, ut semper urna ullamcorper in. Aliquam cursus sem vel mi tempus, ac fermentum est cursus. Maecenas bibendum purus a ante luctus imperdiet vel ac odio.",
    "Fusce sem urna, efficitur et eleifend eu, euismod sit amet velit. Etiam id cursus sapien. Sed iaculis ullamcorper neque, vel porttitor justo mattis ac. Phasellus mi nisi, accumsan sit amet nisi nec, viverra sagittis arcu. Sed neque dolor, iaculis eu auctor quis, commodo quis arcu. Pellentesque sem est, pretium et mattis sed, fringilla nec nunc. Cras lacus lacus, aliquam quis venenatis a, aliquet sit amet leo. Ut et eros orci. Aenean sit amet arcu dolor. Proin euismod diam felis, vel interdum sem tempus id. Integer gravida varius purus, et malesuada ante posuere vel. Maecenas pretium dolor sed ante iaculis, nec posuere dolor rutrum. Sed ultrices pretium risus, id elementum tellus facilisis vel. Mauris semper commodo leo et faucibus.",
    "Nunc id tortor ut metus aliquet semper. Sed neque tellus, bibendum quis nunc ut, efficitur dictum nulla. Curabitur maximus placerat justo. Phasellus lacinia, sem vitae efficitur maximus, purus risus semper sem, eu suscipit nunc mauris nec nisl. Praesent tellus enim, tempus id ante eget, tempus dapibus erat. Fusce a finibus augue. Donec nec nunc et orci posuere venenatis.",
    "Donec sollicitudin sapien ornare, iaculis leo sit amet, facilisis lorem. Fusce molestie nibh eu magna mollis, nec mollis arcu venenatis. Phasellus sagittis tristique venenatis. Phasellus ac orci sit amet sapien posuere dictum at ac purus. Fusce nunc nisl, varius ac sapien a, auctor semper dolor. Sed vitae mi commodo, placerat quam eget, tempor mi. Nam dapibus, ligula in varius congue, arcu lacus blandit orci, quis dictum risus tortor ultrices ligula. Proin varius vel ipsum ut bibendum. Morbi ac dignissim lectus, sed fringilla mi. Quisque ultrices quam sit amet lorem placerat semper. Mauris sed libero imperdiet, interdum libero malesuada, vehicula ligula. Mauris lacinia augue sed malesuada elementum. Donec tempor ligula sit amet ligula pharetra volutpat. Etiam vitae augue nec nibh semper bibendum sed in urna. Nunc aliquam eget eros fermentum semper. Quisque accumsan ante in leo molestie iaculis.",
    "Maecenas semper nunc sed nisl elementum vestibulum. Curabitur ac leo turpis. Nulla venenatis felis vel nisl tempor viverra. Quisque nec tincidunt urna, id tincidunt augue. Suspendisse tortor massa, ornare in ligula vitae, semper porttitor mi. Integer nec eros ut nisi volutpat sodales non sed urna. Vestibulum tempor libero lectus, ac rhoncus sem dictum eu.",
    "Suspendisse potenti. Integer ac molestie libero, in commodo elit. Suspendisse quis interdum dui, id condimentum lorem. Nunc fringilla sed erat dictum tincidunt. Duis eu consectetur nunc. Phasellus viverra lorem mi, eu eleifend diam bibendum non. Cras non cursus magna. Donec sit amet purus tristique nisl congue ultrices non sit amet metus. Vestibulum ut mauris vitae metus molestie pellentesque. Nunc elementum a dui eu fringilla. Nunc sagittis quam sit amet nulla placerat, et scelerisque ex maximus. Phasellus pellentesque lacinia vehicula. Etiam at lorem a risus viverra faucibus tincidunt accumsan eros. Nullam eu imperdiet arcu. Proin nulla risus, efficitur vel posuere in, iaculis eu leo.",
    "Maecenas dui magna, placerat eu tellus vel, interdum placerat enim. Etiam et lectus dui. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed finibus sed ante ac cursus. Suspendisse massa purus, maximus sed quam eu, pellentesque dapibus urna. Aliquam erat volutpat. Mauris odio risus, tincidunt quis bibendum eu, consectetur at elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis eu risus id massa scelerisque tincidunt. Vivamus dolor mi, hendrerit non consequat nec, aliquam non eros. Pellentesque fermentum nunc sed finibus porttitor. Nulla velit velit, condimentum ac arcu nec, bibendum pharetra ante.",
    "Integer quis odio fringilla, ultrices odio elementum, blandit velit. Aenean dictum convallis libero ac interdum. Duis a ante id ante laoreet aliquam. Duis porttitor magna vel augue rutrum, nec faucibus nisi sodales. In interdum sit amet urna laoreet ullamcorper. Morbi ac ex lobortis, hendrerit magna ut, vestibulum quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean ac accumsan quam, ut pellentesque ipsum.",
    "Integer a sapien nec dolor semper porta ac a eros. In non orci et libero vulputate imperdiet. Donec vel pulvinar turpis. Curabitur at varius augue. Mauris feugiat eros vitae nunc mollis, eu dictum est commodo. Vestibulum tincidunt tempor pharetra. Donec sed efficitur augue, nec condimentum lacus. Nulla facilisi. Aliquam ut ante nisl. Duis ac ex nisl. Nulla ullamcorper tristique laoreet. Donec ultrices lectus iaculis lorem venenatis, id congue arcu fringilla.",
    "Donec consequat ante id nisi dapibus varius. Duis sodales sagittis erat venenatis pellentesque. Fusce viverra sollicitudin commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis massa odio, hendrerit eu ullamcorper id, eleifend at urna. Sed rhoncus urna risus, eget porta nisl molestie eget. In pharetra sagittis turpis sit amet pulvinar. Sed facilisis nibh urna, ac placerat sapien rutrum non. Nam ac metus non nisi vehicula tincidunt a sit amet diam. Nam sit amet malesuada metus.",
    "Nam efficitur enim quis vestibulum laoreet. Etiam et efficitur erat, sed imperdiet lorem. Ut a lorem at justo auctor posuere elementum quis felis. Etiam leo orci, egestas id egestas in, gravida ut neque. Etiam tincidunt tortor vel diam vulputate aliquet sit amet non quam. Vestibulum volutpat mauris sit amet dui tristique maximus. Suspendisse eu bibendum magna, non fermentum ipsum. In eget dolor tempus, efficitur leo at, tristique tellus. Vivamus mollis lectus vitae enim gravida, quis hendrerit libero commodo. In hac habitasse platea dictumst. Sed at justo vitae ex venenatis dignissim id sed orci. Donec scelerisque sapien in ligula placerat, nec tempor sapien sollicitudin. Etiam elementum, augue ac maximus aliquet, urna massa euismod nisi, vel auctor sapien urna eu nisi. Quisque venenatis nisi vel tincidunt faucibus. Curabitur laoreet lacinia augue.",
    "Cras iaculis facilisis felis non mattis. Sed sapien enim, tincidunt id enim at, blandit accumsan ex. Pellentesque tristique sed nunc dapibus tristique. Quisque suscipit, nunc sed tincidunt tincidunt, ex turpis feugiat urna, id tempus ligula ligula in lectus. Donec in blandit metus. Sed quis ullamcorper metus, ac feugiat mi. Vivamus lectus risus, aliquet et sapien vel, pellentesque dapibus metus. Praesent vel dui odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis at augue id ex aliquam porttitor vitae sed elit. Nulla ac libero pharetra, scelerisque elit eu, luctus nunc. Cras tincidunt viverra mi, a mollis risus pulvinar id. Pellentesque pretium orci augue, in porttitor nibh tempor in. Morbi pulvinar ipsum in arcu iaculis imperdiet. Ut fringilla nibh non dui laoreet, et molestie augue pulvinar. Suspendisse potenti.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Sed at tempus nisi, in maximus metus. Nullam condimentum molestie nisi, a mattis nibh mattis vitae. Integer nisl velit, bibendum finibus neque at, bibendum eleifend nibh. Curabitur facilisis porta tincidunt. Donec at suscipit metus. Donec pellentesque velit velit, quis pharetra arcu ultrices vitae. Donec vehicula odio in justo varius suscipit. Etiam in malesuada orci, vel tempus erat. Morbi vulputate dolor nec dui tincidunt, sed tempor leo pharetra. Aenean sem ex, pellentesque a lobortis quis, tristique sit amet nisl. Aenean justo lacus, commodo quis mollis vitae, ultrices quis ipsum. Mauris facilisis facilisis mi. Nam finibus scelerisque lacus eu finibus. Proin viverra commodo vulputate.",
    "Nullam nec consectetur nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin ac urna viverra odio dictum hendrerit et vitae augue. Morbi accumsan pretium ligula sit amet elementum. Curabitur a consequat metus. Sed quam eros, volutpat vitae lobortis sit amet, pretium ut sem. In viverra ultrices magna ut euismod. Proin nulla lacus, rutrum malesuada sollicitudin ut, vulputate quis dui. In eget volutpat orci.",
    "Vestibulum ac leo dui. Sed fermentum leo nec tortor varius, semper elementum tellus posuere. Sed nunc turpis, hendrerit quis sodales at, posuere quis tellus. Praesent mollis velit ac laoreet dapibus. Aliquam pretium maximus vestibulum. Vivamus viverra pulvinar eros a malesuada. Maecenas congue laoreet placerat.",
    "Sed feugiat leo ut massa ultricies rhoncus. Fusce augue elit, efficitur eget scelerisque vel, finibus vel lacus. In hac habitasse platea dictumst. Sed id ante non eros feugiat tristique. Integer pharetra tortor sed purus tincidunt, a tempor turpis sodales. In suscipit tempus quam, vel consectetur augue posuere vitae. Donec diam augue, bibendum quis lorem at, laoreet congue purus.",
]

let maxWidth : CGFloat = 300
let font : UIFont = UIFont.systemFontOfSize(14)

